config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :contacts
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
        @contacts = Contact.all
    end
    def new
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.address %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.comments %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/home/index.html.erb
 <!-- Intro Header -->
 <header class="intro">
 <div class="intro-body">
 <div class="container">
 <div class="row">
 <div class="col-md-8 col-md-offset-2">
 <h1 class="brand-heading">CJ COMPUTER SOLUTIONS</h1>
 <p class="intro-text">The best in IT services.<br>Created on July 2014</p>
 <a href="#contact" class="btn btn-circle page-scroll pulse">
 <i class="fa fa-angle-double-down"></i>
 </a>
 </div>
 </div>
 </div>
 </div>
 </header>
 
 
<a href="#download2" class="btn btn-circle page-scroll pulse">
 <i class="fa fa-angle-double-down"></i>
 </a>
 <!-- Download SASS Section -->
 <section id="download2" class="content-section text-center">
 <div class="download-section">
 <div class="container">
 <div class="col-lg-8 col-lg-offset-2">
 <h2><strong>About Us</strong></h2>
 <p>We love what we do</p>

<p>At CJ COMPUTER we are commited to keep both our customers and staff members happy.</p>

<p>We keep our customers satisfied by providing them with great solutions and staff that will help them to develop their ideas and bring them to life. We search for the best staff members and give you the opportunity to talk to them and find the one that will suit your needs.</p>

<p>On the other hand our staff members are always eager to help. We give them the opportunity to choose whether or not to be part of a project and pick the ones they are interested in. They are always looking for new challenges, learning experiences and helping you, the best way they can, to achieve your goals.</p>

<p>By keeping both parts happy we create a great collaborative and growth environment.</p>

<p>Our staff has expertise in a variety of technologies, we can deliver high quality solutions that would help you work  in  the most efficient way.</p>

 </div>
 </div>
 </div>
 </section>

 



 

app/views/layouts/_footer.html.erb
<section id="footer" class="container content-section text-center">
<div class="container">
<!-- Footer -->
 <footer>
 <div class="container text-center">
 <p>Copyright &copy; CJCOMPUTER 2016</p>
 </div>
 </footer>
 </div> 
</section>

 

app/views/layouts/_header.html.erb
<!-- Navigation -->
 <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
 <div class="container">
 <div class="navbar-header">
 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
 <i class="fa fa-bars"></i>
 </button>
 <a class="navbar-brand page-scroll" href="#page-top">
 <i></i> <span class="light"><%= link_to 'Start', home_index_path, class: "fa fa-play-circle" %> </span>
 </a>
 </div>

 <!-- Collect the nav links, forms, and other content for toggling -->
 <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
 <ul class="nav navbar-nav">
 <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
 <li class="hidden">
 <a href="#page-top"></a>
 </li>
 <li>
 <%= link_to 'About', class: "page-scroll" %>
 </li>
 <li>
  <%= link_to 'Services', class: "page-scroll" %>
 </li>
 <li>
 <a class="page-scroll" href="#download2">Download</a>
 </li>
 <li>
 <%= link_to 'Web sites', class: "page-scroll" %>
 </li>
 <li>
 <%= link_to 'Contact us', class: "page-scroll" %> 
 </li>
 </ul>
 </div>
 <!-- /.navbar-collapse -->
 </div>
 <!-- /.container -->
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CJ COMPUTER</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <body>
    <%= render '/layouts/header' %>  
    <%= yield %>
    <%= render '/layouts/footer' %> 
    <%= javascript_include_tag 'application' %>
  </body>
</html>